# export UID=`id -u`; export GID=`id -g`; docker-compose up -d

version: "3.3"

services:

  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    tty: True
    user: $UID:$GID:$USER
    volumes:
      - $HOME/Documents/MS:/tmp/MS


